default: &default
  adapter:  postgresql
  encoding: unicode
  username: commonapp
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_dev

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: backend